# Generated by Django 3.2.5 on 2021-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='clinic/%Y/%m'),
        ),
    ]
