# Generated by Django 3.2.5 on 2021-07-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='sick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='clinic.sick'),
        ),
    ]
