# Generated by Django 3.2.6 on 2021-08-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20210805_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.appointment'),
            preserve_default=False,
        ),
    ]
