# Generated by Django 3.2.6 on 2021-09-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appPrescriptions', to='clinic.appointment'),
        ),
    ]
