# Generated by Django 3.2.6 on 2021-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_alter_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
