# Generated by Django 3.2.6 on 2021-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_prescription_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_time',
            field=models.TimeField(null=True),
        ),
    ]
