# Generated by Django 3.2.6 on 2021-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_appointment_meet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledoctor',
            name='schedule_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='schedulenurse',
            name='schedule_date',
            field=models.DateTimeField(default=None),
        ),
    ]
