# Generated by Django 3.2.6 on 2021-11-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20210928_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='PATIENT', max_length=255, null=True),
        ),
    ]
