export const BOOKING_REQUEST = 'BOOKING_REQUEST'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'
export const BOOKING_RESET = 'BOOKING_RESET'

export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST'
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS'
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL'