export const MEDICAL_LIST_REQUEST = 'MEDICAL_LIST_REQUEST'
export const MEDICAL_LIST_SUCCESS = 'MEDICAL_LIST_SUCCESS'
export const MEDICAL_LIST_FAIL = 'MEDICAL_LIST_FAIL'

export const MEDICAL_UPDATE_REQUEST = 'MEDICAL_UPDATE_REQUEST'
export const MEDICAL_UPDATE_SUCCESS = 'MEDICAL_UPDATE_SUCCESS'
export const MEDICAL_UPDATE_FAIL = 'MEDICAL_UPDATE_FAIL'
export const MEDICAL_UPDATE_RESET = 'MEDICAL_UPDATE_RESET'

export const MEDICAL_CREATE_REQUEST = 'MEDICAL_CREATE_REQUEST'
export const MEDICAL_CREATE_SUCCESS = 'MEDICAL_CREATE_SUCCESS'
export const MEDICAL_CREATE_FAIL = 'MEDICAL_CREATE_FAIL'

export const MEDICAL_DETAILS_REQUEST = 'MEDICAL_DETAILS_REQUEST'
export const MEDICAL_DETAILS_SUCCESS = 'MEDICAL_DETAILS_SUCCESS'
export const MEDICAL_DETAILS_FAIL = 'MEDICAL_DETAILS_FAIL'

